name: questions-consistency

on:
  push:
    branches: [ main ]   # developでも走らせたいなら [ main, develop ] に
  pull_request:

jobs:
  check:
    name: Check Supabase questions consistency
    # フォークPRはSecretsが渡らないのでスキップ
    if: ${{ github.event_name != 'pull_request' || !github.event.pull_request.head.repo.fork }}
    runs-on: ubuntu-latest
    timeout-minutes: 10

    defaults:
      run:
        working-directory: bot_server

    # ★ Secrets を job レベルで注入
    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      # 読み取りだけなら ANON を推奨。スクリプトが Service Role を要求するなら下を使う
      SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
      # SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Verify questions dataset
        run: npm run check:questions
